name: Generate TTL
concurrency: ci-${{ github.ref }}
on:
    push:
      branches:
        - master
      paths-ignore:
        - 'notes.ttl'
        - 'README.md'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3 
            - name: Generate TTL
              id: generate-ttl
              uses: ./actions/notes2rdf
              with:
                notes-root: ./markdown
                base-uri: "https://www/jmoney.dev/notes/notes"
                output-file: ./notes.ttl
            - name: Git status files
              run: git status