name: Generate TTL
concurrency: notes2rdf-${{ github.ref }}
on:
    push:
      branches:
        - master
      paths-ignore:
        - 'notes.ttl'
        - 'README.md'
jobs:
    build:
        runs-on: ubuntu-latest
        env: 
            CI_COMMIT_MESSAGE: Generate new notes.ttl
            CI_COMMIT_AUTHOR: Github Actions
        steps:
            - uses: actions/checkout@v3 
            - name: Generate TTL
              id: generate-ttl
              uses: jmoney/notes2rdf@b9f41cbdd7ce34d355f5c0955ad18593df56a0ff
              with:
                notes-root: ./markdown
                base-uri: "https://www/jmoney.dev/notes/notes"
                output-file: ./notes.ttl
            - name: Verify Changed files
              uses: tj-actions/verify-changed-files@v16
              id: verify-changed-files
              with:
                files: |
                    notes.ttl
            - name: Push notes.ttl updates
              if: steps.verify-changed-files.outputs.files_changed == 'true'
              run: |
                git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
                git config --global user.email "noreply@github.com"
                git add notes.ttl
                git commit --message "${{ env.CI_COMMIT_MESSAGE }}"
                git push