name: Update README.md
concurrency: ci-${{ github.ref }}
on:
    push:
      branches:
        - master
      paths:
        - 'notes.ttl'
jobs:
    build:
        runs-on: ubuntu-latest
        env: 
            CI_COMMIT_MESSAGE: Generate new README
            CI_COMMIT_AUTHOR: Github Actions
        steps:
            - uses: actions/checkout@v3 
            - name: Generate notes catalog
              run: python ./.template/readme/find_markdown.py > notes.json
            - name: Generate README.md
              uses: cuchi/jinja2-action@v1.2.0
              with:
                template: ./.template/readme/README.md.j2
                output_file: README.md
                data_file: notes.json
                data_format: json
            - name: Check if README changed
              id: readme_changed
              run: echo "rc=$(git diff --exit-code --quiet README.md)" >> $GITHUB_OUTPUT
            - name: Push README.md updates
              if: ${{ steps.readme_changed.outputs.rc == '1' }}
              run: |
                git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
                git config --global user.email "noreply@github.com"
                git add README.md
                git commit --message "${{ env.CI_COMMIT_MESSAGE }}"
                git push